-- 마쿠우치(1부 리그) 리키시 본명(실명) 데이터베이스 갱신 스크립트
-- 총 66명 (2025~2026 마쿠우치 등록 선수 전원)

-- 1. 일본 국적 리키시 (일본 본명 한자의 표준 한국어 독음)
UPDATE rikishi SET name = '나카무라 다이키' WHERE external_api_id = 8850; -- 大の里 (中村 泰輝)
UPDATE rikishi SET name = '카마타니 마사카츠' WHERE external_api_id = 20; -- 琴櫻 (鎌谷 将且)
UPDATE rikishi SET name = '오치아이 테츠야' WHERE external_api_id = 8780; -- 伯乃富士 / 前 伯桜鵬 (落合 哲也)
UPDATE rikishi SET name = '타카니시 하야토' WHERE external_api_id = 12; -- 大栄翔 (高西 勇人)
UPDATE rikishi SET name = '이시바시 히로키' WHERE external_api_id = 5; -- 朝乃山 (石橋 広暉)
UPDATE rikishi SET name = '오나미 아츠시' WHERE external_api_id = 14; -- 若隆景 (大波 渥)
UPDATE rikishi SET name = '오나미 미나토' WHERE external_api_id = 15; -- 若元春 (大波 港)
UPDATE rikishi SET name = '호리키리 코우스케' WHERE external_api_id = 22; -- 阿炎 (堀切 洸助)
UPDATE rikishi SET name = '우라 카즈키' WHERE external_api_id = 26; -- 宇良 (宇良 和輝)
UPDATE rikishi SET name = '타카야스 아키라' WHERE external_api_id = 37; -- 高安 (高安 晃)
UPDATE rikishi SET name = '이시오카 미키야' WHERE external_api_id = 8781; -- 尊富士 (石岡 弥輝也)
UPDATE rikishi SET name = '타케이 사쿠타로' WHERE external_api_id = 70; -- 熱海富士 (武井 朔太郎)
UPDATE rikishi SET name = '테바카리 토시키' WHERE external_api_id = 11; -- 琴勝峰 (手計 富士紀)
UPDATE rikishi SET name = '테바카리 타이키' WHERE external_api_id = 86; -- 琴栄峰 (手計 太希)
UPDATE rikishi SET name = '사카구치 유키' WHERE external_api_id = 23; -- 平戸海 (坂口 雄貴)
UPDATE rikishi SET name = '니시카와 토우키' WHERE external_api_id = 75; -- 豪ノ山 (西川 登輝)
UPDATE rikishi SET name = '키자키 신지' WHERE external_api_id = 87; -- 美ノ海 (木﨑 信志)
UPDATE rikishi SET name = '이시이 노부아키' WHERE external_api_id = 31; -- 隆の勝 (石井 伸明)
UPDATE rikishi SET name = '야마모토 다이키' WHERE external_api_id = 13; -- 一山本 (山本 大生)
UPDATE rikishi SET name = '오가사와라 류세이' WHERE external_api_id = 34; -- 錦富士 (小笠原 隆聖)
UPDATE rikishi SET name = '나야 코노스케' WHERE external_api_id = 36; -- 王鵬 (納谷 幸之介)
UPDATE rikishi SET name = '이오하라 카즈나리' WHERE external_api_id = 29; -- 翠富士 (庵原 一成)
UPDATE rikishi SET name = '쇼다이 나오야' WHERE external_api_id = 28; -- 正代 (正代 直也)
UPDATE rikishi SET name = '오미치 히사시' WHERE external_api_id = 24; -- 御嶽海 (大道 久司)
UPDATE rikishi SET name = '이와사키 마사야' WHERE external_api_id = 21; -- 翔猿 (岩崎 正也)
UPDATE rikishi SET name = '와타나베 유키' WHERE external_api_id = 18; -- 竜電 (渡辺 裕樹)
UPDATE rikishi SET name = '쿠마가이 테츠야' WHERE external_api_id = 19; -- 錦木 (熊谷 徹也)
UPDATE rikishi SET name = '타츠 아야야' WHERE external_api_id = 27; -- 輝 (達 綾哉)
UPDATE rikishi SET name = '마츠무라 카나메' WHERE external_api_id = 30; -- 佐田の海 (松村 要)
UPDATE rikishi SET name = '카와바타 메이세이' WHERE external_api_id = 32; -- 明生 (川畑 明生)
UPDATE rikishi SET name = '타니마츠 쇼토' WHERE external_api_id = 38; -- 湘南乃海 (谷松 将人)
UPDATE rikishi SET name = '사이토 다이스케' WHERE external_api_id = 82; -- 北の若 (齋藤 大輔)
UPDATE rikishi SET name = '츠카하라 타카아키' WHERE external_api_id = 101; -- 栃大海 (塚原 隆明)
UPDATE rikishi SET name = '히가시 류키' WHERE external_api_id = 102; -- 藤青雲 (東 龍輝)
UPDATE rikishi SET name = '토미에 히데키' WHERE external_api_id = 104; -- 時疾風 (冨栄 秀喜)
UPDATE rikishi SET name = '후카자와 세이야' WHERE external_api_id = 119; -- 欧勝海 (深沢 成矢)
UPDATE rikishi SET name = '타카하시 유타' WHERE external_api_id = 8783; -- 白熊 (高橋 優太)
UPDATE rikishi SET name = '미나미 유타' WHERE external_api_id = 127; -- 友風 (南 友太)
UPDATE rikishi SET name = '사와다 히토시' WHERE external_api_id = 135; -- 日翔志 (沢田 日登志)
UPDATE rikishi SET name = '카요 요시무네' WHERE external_api_id = 8871; -- 嘉陽 (嘉陽 快宗)
UPDATE rikishi SET name = '이시자키 타쿠마' WHERE external_api_id = 8806; -- 朝紅龍 (石崎 拓馬)
UPDATE rikishi SET name = '타케다 쇼이치로' WHERE external_api_id = 8839; -- 若ノ勝 (竹田 章一郎)
UPDATE rikishi SET name = '사이토 세이고' WHERE external_api_id = 8847; -- 藤ノ川 (齋藤 成剛)
UPDATE rikishi SET name = '쿠사노 나오야' WHERE external_api_id = 8860; -- 義ノ富士 (草野 直哉)
UPDATE rikishi SET name = '이시자키 료마' WHERE external_api_id = 8864; -- 朝翠龍 (石崎 涼馬)
UPDATE rikishi SET name = '카와부치 카즈마' WHERE external_api_id = 8873; -- 一意 (川渕 一意)
UPDATE rikishi SET name = '고시마 마사하루' WHERE external_api_id = 8963; -- 藤凌駕 (五島 雅治)
UPDATE rikishi SET name = '엔도 쇼타' WHERE external_api_id = 17; -- 遠藤 (遠藤 聖大)
UPDATE rikishi SET name = '나카무라 다이키' WHERE external_api_id = 27; -- 北勝富士 (中村 大輝)
UPDATE rikishi SET name = '스기야마 다이스케' WHERE external_api_id = 25; -- 宝富士 (杉山 大輔)
UPDATE rikishi SET name = '이와사키 타쿠야' WHERE external_api_id = 60; -- 英乃海 (岩崎 拓也)

-- 2. 외국 국적 리키시 (현지 본명의 한국어 표기)
UPDATE rikishi SET name = '수가르라그차 뱜바수렌' WHERE external_api_id = 19; -- 豊昇龍 (몽골, Sugarragchaa Byambasuren)
UPDATE rikishi SET name = '뱜바추룬 라그바수렌' WHERE external_api_id = 10; -- 霧島 (몽골, Byambachuluun Lkhagvasuren)
UPDATE rikishi SET name = '바트자르갈 뭉흐오르길' WHERE external_api_id = 16; -- 玉鷲 (몽골, Batjargal Munkh-Orgil)
UPDATE rikishi SET name = '간바타르 뭉흐사이한' WHERE external_api_id = 33; -- 千代翔馬 (몽골, Ganbaatar Munkhsaikhan)
UPDATE rikishi SET name = '아마르사나 아마트부신' WHERE external_api_id = 74; -- 狼雅 (몽골, Amarsanaa Amartuvshin)
UPDATE rikishi SET name = '퓌레브수렌 델게르바야르' WHERE external_api_id = 79; -- 欧勝馬 (몽골, Pürevsüren Delgerbayar)
UPDATE rikishi SET name = '예르신 발타굴' WHERE external_api_id = 71; -- 金峰山 (카자흐스탄, Yersin Baltagul)
UPDATE rikishi SET name = '세르히 소콜로우스키' WHERE external_api_id = 107; -- 獅司 (우크라이나, Serhii Sokolovskyi)
UPDATE rikishi SET name = '에르덴비레그 엔흐만라이' WHERE external_api_id = 126; -- 玉正鳳 (몽골, Erdenebileg Enkhmanlai)
UPDATE rikishi SET name = '아스하다' WHERE external_api_id = 8794; -- 大青山 (중국 내몽골, 阿斯哈達 / Asuhada)
UPDATE rikishi SET name = '라그차 잠인톡토흐' WHERE external_api_id = 8837; -- 朝白龍 (몽골, Ragchaa Jamts)
UPDATE rikishi SET name = '바트자르갈 초이질수렌' WHERE external_api_id = 8854; -- 阿武剋 (몽골, Batjargal Chojilsuren)
UPDATE rikishi SET name = '다닐로 야브후시신' WHERE external_api_id = 8856; -- 安青錦 (우크라이나, Danil Yavhusishyn)
UPDATE rikishi SET name = '우스흐바야르 데미데잠츠' WHERE external_api_id = 8874; -- 寿之富士 (몽골, Usukhbayar Demidejamts)
UPDATE rikishi SET name = '간툴가 간에르데네' WHERE external_api_id = 45; -- 照ノ富士 (몽골, Gantulga Gan-Erdene)
